### ISSUE TITLE
WebRTC demo page errors

### ISSUE THREAD

**Issue by M0LTE** [gavv/webrtc-cli#8] opened 2020-12-21 15:27 UTC
When I open https://gavv.github.io/webrtc-cli/ I get:

Creating session...
Adding microphone to session...
TypeError: Cannot read property 'sdp' of null

Chrome latest on Windows 10.

**Comment by groberts817** [comment] 2021-01-22 16:50
I changed this line: https://github.com/gavv/webrtc-cli/blob/master/docs/index.html#L94 and the one below it to:
```
pc.setLocalDescription(offer).then(function() {
  document.getElementById('offer').value = pc.localDescription.sdp
});
```
since setLocalDescription is an asynchronous function that returns a promise. The localDescription is not yet set in the original code.

**Comment by gavv** [comment] 2021-02-21 10:27
@M0LTE @groberts817 thanks! I was able to reproduce the issue and apply the fix. Pushed to master. Closing this, but feel free to reopen if it's not fixed for you.

**Closed as completed by gavv** 2021-02-21 10:27 UTC
